### ISSUE TITLE
Benchmark(s)

### ISSUE THREAD

**Issue by amorphid** [IRog/simpler_cache#1]
Hi!  I enjoyed your talk at the Elixir meetup.  If you're able & willing, could you share the code you used to generate the benchmarks mentioned in the README?  Thanks!

P.S.  Apologies if they are in the codebase.  I didn't see them.

**Comment by v-kat** [comment]
Please see https://github.com/IRog/simpler_cache/tree/benchmark although I haven't updated them in a bit.

**Comment by amorphid** [comment]
I must have been completely zonked when I asked, and I'm not sure how I missed `mix run benchmarks/cache_benchmark.exs`.  Thank you for politely pointing me to the thing I somehow couldn't see in plain sight :)

**Comment by amorphid** [comment]
Ah, it was the benchmark branch!  Glad to know I'm not totes cray cray.
